### ISSUE TITLE
KeyError when attempting to get an article wikipedia

### ISSUE THREAD

**Issue by Netanel-M** [iamjake648/jasper-wiki#1]
With the current version of jasper, the wiki module crashes when attempting to search wikipedia.
When jasper is prompted with keyword wiki, it goes into active listen mode at which point it shortly crashes thereafter.
I am getting the following traceback:

`Traceback (most recent call last):
  File "/home/test/jasper/client/brain.py", line 73, in query
    module.handle(text, self.mic, self.profile)
  File "/home/test/jasper/client/modules/Wiki.py", line 14, in handle
    get_wiki(text,mic)
  File "/home/test/jasper/client/modules/Wiki.py", line 28, in get_wiki
    final = output[output.keys()[0]]["extract"]
KeyError: 'extract'`

I'll try digging around, but I'm not yet familiar with the wikipedia api.

**Comment by iamjake648** [comment]
Have you tried a couple of different articles or article prompts? The exact same method is available in the MethodTest file, just minus the voice. A check should be added for that non existing key though.

**Comment by Netanel-M** [comment]
After further examination the problem does not seem to persist, perhaps there's clause to try and catch that error anyway. I'm not sure what caused it. As I used the same phrase to query wikipedia multiple times and have had no problems since.

**Comment by iamjake648** [comment]
Awesome, thanks for your feedback! I never actually got around to testing this on an actual Jasper, so I'm glad someone did!
