### ISSUE TITLE
Wiki only responds to keyword wicky

### ISSUE THREAD

**Issue by Netanel-M** [iamjake648/jasper-wiki#2]
Unusual issue, when I say "wiki" and the stt engine translates it to "wicky" the module loads, but when the stt engine translates it to "wiki" the module is ignored.

**Comment by Netanel-M** [comment]
I seemed to have fixed it, issue is in Wiki.py. I switched line wiki= bool(re.search(r'\Wiki\b',text, re.IGNORECASE)) with wiki= bool(re.search(r'\wiki\b',text, re.IGNORECASE)) in function is_valid

**Comment by iamjake648** [comment]
Yeah the different speech engines are pretty bad at picking up "Wiki" and they all handle it differently. Should be easy enough to change the keyword for your engine though. Not sure why changing that line would do anything - you are just changing a capital letter on a string that is already ignoring case.
